name: meu_caixa_flutter
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # https://pub.dev/packages/intl
  intl: 0.16.1
  # https://pub.dev/packages/firebase_core
  firebase_core: 0.5.1
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: 6.1.0
  # https://pub.dev/packages/firebase_auth
  firebase_auth: 0.18.2
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: 0.14.2
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: 0.2.2
#  # https://pub.dev/packages/modal_progress_hud
#  modal_progress_hud: 0.1.3
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.12+2
  # https://pub.dev/packages/flutter_masked_text
  flutter_masked_text: 0.8.0
  # https://pub.dev/packages/package_info
  package_info: 0.4.3
  # https://pub.dev/packages/email_validator
  email_validator: 1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true

  assets:
    - images/
